version: '3'

services:
  app:
    build: ./
    container_name: wordle_api
    ports:
      - '3333:3333'
    environment:
      - APP_PORT=3333
      - MONGO_CONNECTION_STRING=mongodb+srv://user-01:KqjPmk99mtenka4i@cluster0.bp2fwus.mongodb.net/wordle?retryWrites=true&w=majority&appName=Cluster0
      - AI_CORTEX_URL=https://api.textcortex.com/v1
      - AI_CORTEX_TOKEN=gAAAAABlafcOh97ylFeju6XhsrWbheKEs9LxRmg-OzbCCrIgNE8orUrmximJ2XqXbNmIPPJxwlRiHHLDgY_tNtal732ixAFUBcJKpLzo7Jl4J3goJvayyK1ShNCipGqfkLTwXU_-wlCR
      - AI_COHERE_URL=https://api.cohere.ai
      - AI_COHERE_TOKEN=BYiTKBaoBWlv8KIsO3NcwqNra4lDb1xwIN6yeZ6V
    # depends_on:
    #   - db
    # networks:
    #   - wordle_network

  # db:
  #   image: mongo:latest
  #   container_name: wordle_db
  #   ports:
  #     - '27018:27017'
  #   volumes:
  #     - ./data:/data/db
  #   networks:
  #     - wordle_network
# networks:
#   wordle_network:
#     driver: bridge
